### ISSUE TITLE
Add a "call to action" on howto add missing samples

### ISSUE THREAD

**Issue by brunetton** [sfzinstruments/sfzinstruments.github.io#8]
Hi 
Why not add some informations about howto contribute to add missing instruments samples ? Like

> This instrument haven't any sample yet. Why don't you create it ? 
> To add a missing sample, clone the repository (https://github.com/sfzinstruments/sfzinstruments.github.io), create this file: `assets/audio/{instrument_category}/{instrument_name}.mp3` and submit a PR

(or only add a link to the Github wiki that explains howto contribute)

I wanted to contribute and it took me some time to grep and understand how to add missing samples.

What do you think about that ?

Thanks !

**Comment by redtide** [comment]
Hello! Thank you for the PRs. I thought the [Wiki page](https://github.com/sfzinstruments/sfzinstruments.github.io/wiki/Add-Instruments) was enough, what I should add other than a link to the README file?

**Comment by redtide** [comment]
Hope is OK in 30b1dbf

**Comment by brunetton** [comment]
🤔 I wasn't thinking about the repo, it's the dark side of the moon for front users; I was talking about the front, the UI ! 

Here is the path I followed:
- I'm looking for a keyboard synth
- I went to home: https://sfzinstruments.github.io (via google, NOT github of course)
- I'm searching for a keyboard so I click on Keyboards and I'm now on https://sfzinstruments.github.io/keyboards
- here there's no much choice so I open the only one: https://sfzinstruments.github.io/keyboards/sforzatron

The informations div gives me:
- Author: Plogue

I downloaded the instrument, tested it.

How on earth am I supposed to imagine that I could if I wanted contribute to the project to send some samples of this instrument ? To me honest I discovered it totally randomly browsing for other categories and I came across an instrument that had a sample. So I was very surprised and I thought: «ow wow, HOW did thy do here ?». As I explained in the issue, I read the README and as I didn't found anything I jumped onto the code and did some greps to find.

> I thought the [Wiki page](https://github.com/sfzinstruments/sfzinstruments.github.io/wiki/Add-Instruments) was enough

I'm really not used to projects that uses wiki. I've never been part of a team that used the Wiki, because it's too separated from the code (2 repos to clone). I didn't seen it !

> what I should add other than a link to the README file?

For Github a link in the README is 100% OK to me ! But for end user something in the front to call to action is necessary IMHO.

Thanks !

**Comment by redtide** [comment]
The way I know to contribute is to read the wiki instructions, clone the site, apply the changes and file a PR, I have no idea how to avoid this except join our Discord or send by email and let us to do the update. The only CTA we have, IIUC, is at the bottom of each page, but only for the current page content.

**Comment by DSmolken** [comment]
Yeah, uploading audio demos would require being able to use Github currently, or contacting us via Discord. We could potentially add a way to publish user demos and videos, but this would require a very large rebuild of the way the site currently works.

Of course making it easier for people who are not familiar with Github and don't have their own hosting to contribute instruments would also be potentially very helpful. but, well, it's certainly not something we could implement easily or quickly.

**Comment by brunetton** [comment]
@redtide It's amazing how you do not get my point ! I'm not a native English writer but this is the very first time in my Github discussions that I've this level of misunderstanding.

I'll try a last time before moving on: 

- I'm NOT saying that PRs are a bad way to contribute, read my initial writing here
- I'm just saying that while USING the website (as a user, NOT a member of the devs team), I should have been warned that I COULD contribute
   - If I've the technical skills, ie knowing Git: using PRs
   - If not contacting the team using mail, discord or any other way

For now if a user WANTED to contribute (like it was my case) there's 90% chances that the project miss this potential contribution because users just won't go to Github and read readme to add data to the website. I personally do it ONLY if I want to modify the website ITSELF, not its CONTENT (adding data is not modifying website itself, website shows data).

## Super summary with images

I'm just saying that instead of:

  ![image](https://user-images.githubusercontent.com/86322/217809540-6bef5c28-bcbe-41d5-ad89-494a2b7b73ac.png)

Let's show this to users:

  ![image](https://user-images.githubusercontent.com/86322/217811509-05b9a700-8a8c-4841-a3ef-16d7857e47d9.png)

Hoping that this make it clearer !

(finally it would have taken me less time to do it than writing here !)
